# Generated by Django 4.1 on 2024-06-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo', '0002_delete_fishinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('date', models.DateField()),
                ('latin_name', models.CharField(max_length=30)),
                ('count', models.IntegerField()),
                ('mean_length', models.FloatField()),
                ('mean_weight', models.FloatField()),
            ],
        ),
    ]
