# Generated by Django 5.0.6 on 2024-06-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo', '0003_fishinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.IntegerField()),
                ('temp', models.FloatField()),
                ('pH', models.FloatField()),
                ('Ox', models.FloatField()),
                ('Dao', models.FloatField()),
                ('Zhuodu', models.FloatField()),
                ('Yandu', models.FloatField()),
            ],
        ),
    ]
